version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_container
    ports:
      - "8004:8004"
    volumes:
      - .:/app 
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
